### ISSUE TITLE
Question: Ignoring binomial parameters in a ZOIB model

### ISSUE THREAD

**Issue by OmidGhasemi21** [mvuorre/mvuorre.github.io#2]
Hi Matti,

First, thanks for all your amazing blog posts. 

I have a simple question about using zero-one-inflated beta family. In your blogpost, you have used the following formula:

```r
zoib_model <- bf(
  Rating ~ group,
  phi ~ group,
  zoi ~ group,
  coi ~ group, 
  family = zero_one_inflated_beta()
)
```
I was wondering if it is necessary to model `phi`, `zoi`, and `coi` or it is OK to have a model like:

```r
zoib_model <- bf(
  Rating ~ group,
  family = zero_one_inflated_beta()
)
```

I have a model with 4 predictors and modeling each parameter would make the model super complex. Plus, as in your blog post, I am interested in the beta distribution mean, and not the other parameters.

**Comment by mvuorre** [comment]
Hi and thank you for the kind words!

It's very hard for me to say if its ok or not. Sometimes even if you are not interested in some parameters you should include them because not including can change the estimate and meaning of the other parameters that you are interested in. So, I'm sorry but its too difficult to say anything without a specific context.

**Comment by OmidGhasemi21** [comment]
You are right. thank you again for your response and for your incredible posts.
